name: blaznest-project

services:
  app:
    build:
        context: .
        dockerfile: Dockerfile
    image: blazenest-image
    container_name: blazenest-container
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production
