# Generated by Django 5.1.7 on 2025-03-23 14:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprenuership_hub', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='coworking',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='coworking/'),
        ),
        migrations.AlterField(
            model_name='coworking',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, related_name='coworking', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='events/'),
        ),
        migrations.AlterField(
            model_name='incubator',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='incubator/'),
        ),
    ]
