# Generated by Django 5.1.7 on 2025-05-06 10:11

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0002_alter_accommodation_accommodation_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
